<#
.SYNOPSIS
    Generates scripts\ and catalog.toml from apps.json + src\engine.ps1.

.DESCRIPTION
    Run this after editing apps.json or src\engine.ps1, then commit everything it changed.
    CI runs it too and fails if the committed files don't match.

      scripts\install-<id>.ps1   one Kura action per app
      scripts\install-apps.ps1   one "pick from a list" action for all apps (optional)
      catalog.toml               the Kura action list

    Each generated script is the engine with the whole apps.json pasted in, so it runs on
    its own - Kura caches it, and it can be copied anywhere (PDQ, a USB stick).

    Works in Windows PowerShell 5.1 and PowerShell 7.

.EXAMPLE
    .\build.ps1
#>
[CmdletBinding()]
param()

# ----- Settings -----------------------------------------------------------------------
$ActionIdPrefix    = 'spot-install-'   # Kura action ids: spot-install-chrome, ...
$IncludeMenuAction = $true             # also publish the all-apps menu (install-apps.ps1)
# Kura category for the actions. 'install' puts them all together; set to $null to use
# each app's own category from apps.json (browsers, communication, utilities, ...).
$CatalogCategory   = 'install'
# --------------------------------------------------------------------------------------

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Read-Text([string]$Path) {
    return ([IO.File]::ReadAllText((Join-Path $root $Path), $utf8)).TrimStart([char]0xFEFF) -replace "`r`n", "`n"
}

function Write-TextFile([string]$Path, [string]$Text, [string]$Eol) {
    $Text = ($Text -replace "`r`n", "`n")
    if ($Eol -eq 'crlf') { $Text = $Text -replace "`n", "`r`n" }
    $full = Join-Path $root $Path
    $enc = $utf8
    # Windows PowerShell 5.1 reads BOM-less files as ANSI; add a BOM if anything isn't ASCII
    if ($Path -like '*.ps1' -and $Text -match '[^\x00-\x7F]') { $enc = New-Object System.Text.UTF8Encoding($true) }
    $old = $null
    if (Test-Path -LiteralPath $full) { $old = [IO.File]::ReadAllText($full, $enc) }
    if ($old -ne $Text) {
        [IO.File]::WriteAllText($full, $Text, $enc)
        Write-Host "  wrote     $Path" -ForegroundColor Green
    } else {
        Write-Host "  unchanged $Path" -ForegroundColor DarkGray
    }
}

function ConvertTo-TomlString([string]$Value) {
    $sb = New-Object System.Text.StringBuilder
    foreach ($ch in $Value.ToCharArray()) {
        switch ($ch) {
            '\' { [void]$sb.Append('\\') }
            '"' { [void]$sb.Append('\"') }
            "`n" { [void]$sb.Append('\n') }
            "`r" { }
            "`t" { [void]$sb.Append('\t') }
            default {
                if ([int]$ch -lt 32) { [void]$sb.Append(('\u{0:X4}' -f [int]$ch)) } else { [void]$sb.Append($ch) }
            }
        }
    }
    return '"' + $sb.ToString() + '"'
}

# ----- Load inputs --------------------------------------------------------------------
$engine = Read-Text 'src/engine.ps1'
$manifestText = (Read-Text 'apps.json').TrimEnd()
$apps = @(($manifestText | ConvertFrom-Json).apps)
if (-not $apps.Count) { throw 'apps.json has no apps' }

foreach ($a in $apps) {
    if ([string]$a.id -notmatch '^[a-z0-9][a-z0-9-]*$') { throw "Bad app id '$($a.id)' - use lowercase letters, digits and dashes" }
    if ($a.id -in @('apps', 'all', 'updates')) { throw "App id '$($a.id)' is reserved" }
}
$dupes = @($apps | Group-Object id | Where-Object Count -gt 1)
if ($dupes) { throw "Duplicate app id(s): $($dupes.Name -join ', ')" }
# The list is pasted into a single-quoted here-string, which ends at a line starting with '@
if ($manifestText -match "(?m)^'@") { throw "apps.json can't contain a line starting with '@" }

$pattern = '(?s)#region embedded\n.*?#endregion embedded'
if ($engine -notmatch $pattern) { throw 'src/engine.ps1 is missing the #region embedded block' }

function New-Script([string]$AppId, [string]$Title) {
    $idLiteral = '$null'
    if ($AppId) { $idLiteral = "'$AppId'" }
    $block = "#region embedded`n`$EmbeddedAppId = $idLiteral`n`$EmbeddedManifest = @'`n$manifestText`n'@`n#endregion embedded"
    $header = "# GENERATED by build.ps1 from apps.json + src/engine.ps1 - edit those, not this file.`n# $Title`n`n"
    # MatchEvaluator so '$' in the block is never treated as a regex substitution
    $body = [regex]::Replace($engine, $pattern, [System.Text.RegularExpressions.MatchEvaluator] { param($m) $block })
    return $header + $body
}

# ----- Generate -----------------------------------------------------------------------
Write-Host 'Generating scripts and catalog...' -ForegroundColor Cyan
New-Item -ItemType Directory -Path (Join-Path $root 'scripts') -Force | Out-Null
$wanted = @()

$toml = New-Object System.Collections.Generic.List[string]
$toml.Add('# Kura action catalog - published source.')
$toml.Add('# GENERATED by build.ps1 from apps.json - edit apps.json and re-run build.ps1.')
$toml.Add('# Add this repo to Kura with the raw URL of this file.')
$toml.Add('# Scripts live in scripts/ beside this file. Flat, no subfolders.')

foreach ($a in $apps) {
    $file = "install-$($a.id).ps1"
    $wanted += $file
    Write-TextFile "scripts/$file" (New-Script $a.id "App: $($a.name) ($($a.id))") 'crlf'

    $category = $CatalogCategory
    if (-not $category) { $category = ([string]$a.category).ToLowerInvariant() }
    $desc = "Installs or updates $($a.name) with the latest version from the vendor. Shows the installed and latest version first, then asks: silent install, interactive install, or cancel."
    if ($a.notes) { $desc += " Note: $($a.notes)" }
    $admin = 'true'
    if ($a.perUser) { $admin = 'false' }

    $toml.Add('')
    $toml.Add('[[action]]')
    $toml.Add("id = $(ConvertTo-TomlString ($ActionIdPrefix + $a.id))")
    $toml.Add("name = $(ConvertTo-TomlString ('Install ' + $a.name))")
    $toml.Add("category = $(ConvertTo-TomlString $category)")
    $toml.Add("description = $(ConvertTo-TomlString $desc)")
    $toml.Add("requires_admin = $admin")
    $toml.Add('destructive = false')
    $toml.Add("run = { type = `"script`", script = $(ConvertTo-TomlString $file) }")
}

if ($IncludeMenuAction) {
    $file = 'install-apps.ps1'
    $wanted += $file
    Write-TextFile "scripts/$file" (New-Script $null 'All apps - pick from a list') 'crlf'
    $category = $CatalogCategory
    if (-not $category) { $category = 'install' }
    $toml.Add('')
    $toml.Add('[[action]]')
    $toml.Add("id = $(ConvertTo-TomlString ($ActionIdPrefix + 'apps'))")
    $toml.Add('name = "Install / Update Apps (pick from a list)"')
    $toml.Add("category = $(ConvertTo-TomlString $category)")
    $toml.Add('description = "Shows installed vs latest version for every app in kura-apps and installs or updates the ones you pick. Type updates to update everything that is out of date."')
    $toml.Add('requires_admin = true')
    $toml.Add('destructive = false')
    $toml.Add("run = { type = `"script`", script = $(ConvertTo-TomlString $file) }")
}

Write-TextFile 'catalog.toml' (($toml -join "`n") + "`n") 'lf'

# Remove scripts for apps that were taken out of apps.json
foreach ($f in @(Get-ChildItem -LiteralPath (Join-Path $root 'scripts') -Filter '*.ps1')) {
    if ($f.Name -notin $wanted) {
        Remove-Item -LiteralPath $f.FullName -Force
        Write-Host "  removed   scripts/$($f.Name)" -ForegroundColor Yellow
    }
}
Write-Host ("Done: {0} app action(s){1}." -f $apps.Count, $(if ($IncludeMenuAction) { ' + menu' } else { '' })) -ForegroundColor Cyan
