# GENERATED by build.ps1 from apps.json + src/engine.ps1 - edit those, not this file.
# App: ShareX (sharex)

# Kura elevates before launching scripts, so there is no self-elevation here.
# Outside Kura, run from an elevated PowerShell.

<#
.SYNOPSIS
    Installs the latest version of common apps straight from the vendor, for machines
    without the Microsoft Store or winget.

.DESCRIPTION
    This is the shared engine. build.ps1 copies it into every script in scripts\ and
    embeds the app definitions from apps.json:
      scripts\install-<id>.ps1  - one app: shows installed vs latest, then asks
      scripts\install-apps.ps1  - every app, as a pick-from-a-list menu

    Single-app script:
      - already on the latest version -> reinstall (silent / interactive) or cancel
      - older or not installed         -> install silently, interactively, or cancel
      -Unattended installs/updates silently with no prompts (PDQ, RMM, scheduled task).

    Interactive (default): shows a menu with installed vs. latest versions. For each app
    you pick:
      - already on the latest version -> reinstall (silent / interactive) or cancel
      - older or not installed         -> install silently, interactively, or cancel

    Unattended (-App): no prompts. Good for PDQ Deploy, RMM tools, or scheduled tasks.

.PARAMETER Manifest
    Path or http(s) URL to an apps.json to use instead of the embedded app list.

.PARAMETER Unattended
    Single-app scripts only. Install/update this app with no prompts; skips it if it's
    already current (add -Force to reinstall). Same as -App <id>.

.PARAMETER App
    Unattended mode. App ids to install (see -List), or 'all' / 'updates'.

.PARAMETER Mode
    Unattended mode only. Silent (default) or Interactive.

.PARAMETER Force
    Unattended mode only. Reinstall even if the app is already on the latest version.

.PARAMETER CheckFeeds
    Resolve the latest version + download URL for every app, check each download
    URL answers, print the results and exit (1 if any failed). Installs nothing.
    Used by the repo's scheduled CI job to catch vendors changing their links.

.PARAMETER List
    Print the app table (installed vs latest) and exit.

.PARAMETER SkipSignatureCheck
    Don't require a valid Authenticode signature on downloaded installers.

.EXAMPLE
    .\install-chrome.ps1
    Shows Chrome's installed vs latest version and asks what to do.

.EXAMPLE
    .\install-chrome.ps1 -Unattended
    Silently installs/updates Chrome; does nothing if it's already current.

.EXAMPLE
    .\install-apps.ps1 -App updates
    Silently updates every app that is installed and out of date.
#>
[CmdletBinding()]
param(
    [string]$Manifest,
    [string[]]$App,
    [ValidateSet('Silent', 'Interactive')]
    [string]$Mode = 'Silent',
    [switch]$Force,
    [switch]$List,
    [switch]$CheckFeeds,
    [switch]$Unattended,
    [switch]$SkipSignatureCheck,
    [string]$DownloadPath = (Join-Path ([IO.Path]::GetTempPath()) 'KuraApps'),
    [switch]$KeepDownloads
)

# ----- Embedded app list (build.ps1 fills this in; empty in src\engine.ps1) ---------------
#region embedded
$EmbeddedAppId = 'sharex'
$EmbeddedManifest = @'
{
  "schemaVersion": 1,
  "apps": [
    {
      "id": "chrome",
      "name": "Google Chrome",
      "category": "Browsers",
      "notes": "Latest = the stable build at the widest rollout, which is what the enterprise MSI serves.",
      "detect": {
        "files": [
          "%ProgramFiles%\\Google\\Chrome\\Application\\chrome.exe",
          "%ProgramFiles(x86)%\\Google\\Chrome\\Application\\chrome.exe"
        ]
      },
      "latest": {
        "type": "json",
        "url": "https://versionhistory.googleapis.com/v1/chrome/platforms/win64/channels/stable/versions/all/releases?filter=endtime=none&order_by=fraction%20desc",
        "path": "releases[0].version"
      },
      "download": {
        "url": "https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi",
        "fileName": "googlechromestandaloneenterprise64.msi"
      },
      "installer": {
        "type": "msi",
        "silentArgs": "/qn /norestart",
        "interactiveArgs": ""
      }
    },
    {
      "id": "firefox",
      "name": "Mozilla Firefox",
      "category": "Browsers",
      "detect": {
        "displayName": "^Mozilla Firefox( \\(x64|$)"
      },
      "latest": {
        "type": "json",
        "url": "https://product-details.mozilla.org/1.0/firefox_versions.json",
        "path": "LATEST_FIREFOX_VERSION"
      },
      "download": {
        "url": "https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=en-US",
        "fileName": "Firefox-{version}-x64.msi"
      },
      "installer": {
        "type": "msi",
        "silentArgs": "/qn /norestart",
        "interactiveArgs": ""
      }
    },
    {
      "id": "edge",
      "name": "Microsoft Edge",
      "category": "Browsers",
      "detect": {
        "files": [
          "%ProgramFiles(x86)%\\Microsoft\\Edge\\Application\\msedge.exe",
          "%ProgramFiles%\\Microsoft\\Edge\\Application\\msedge.exe"
        ]
      },
      "latest": {
        "type": "script",
        "script": [
          "$r = Invoke-RestMethod -Uri 'https://edgeupdates.microsoft.com/api/products' -UseBasicParsing",
          "$rel = ($r | Where-Object { $_.Product -eq 'Stable' }).Releases |",
          "  Where-Object { $_.Platform -eq 'Windows' -and $_.Architecture -eq 'x64' } |",
          "  Sort-Object { [version]$_.ProductVersion } -Descending | Select-Object -First 1",
          "$msi = $rel.Artifacts | Where-Object { $_.ArtifactName -eq 'msi' } | Select-Object -First 1",
          "@{ Version = $rel.ProductVersion; Url = $msi.Location }"
        ]
      },
      "download": {
        "fileName": "MicrosoftEdgeEnterpriseX64-{version}.msi"
      },
      "installer": {
        "type": "msi",
        "silentArgs": "/qn /norestart",
        "interactiveArgs": ""
      }
    },
    {
      "id": "discord",
      "name": "Discord",
      "category": "Communication",
      "perUser": true,
      "notes": "Per-user install. Run as the logged-in user; skipped under SYSTEM unless named explicitly.",
      "detect": {
        "displayName": "^Discord$"
      },
      "latest": {
        "type": "redirect",
        "url": "https://discord.com/api/download?platform=win",
        "regex": "/(?<version>\\d+\\.\\d+\\.\\d+)/[^/]*\\.exe"
      },
      "download": {
        "fileName": "DiscordSetup-{version}.exe"
      },
      "installer": {
        "type": "exe",
        "silentArgs": "-s",
        "interactiveArgs": ""
      }
    },
    {
      "id": "zoom",
      "name": "Zoom Workplace",
      "category": "Communication",
      "notes": "Installed version is read from Zoom.exe's file version so it lines up with the 4-part version in Zoom's download URL.",
      "detect": {
        "files": [
          "%ProgramFiles%\\Zoom\\bin\\Zoom.exe",
          "%APPDATA%\\Zoom\\bin\\Zoom.exe"
        ],
        "displayName": "^Zoom( Workplace)?( \\(64-bit\\))?$"
      },
      "latest": {
        "type": "redirect",
        "url": "https://zoom.us/client/latest/ZoomInstallerFull.msi?archType=x64",
        "regex": "/prod/(?<version>[\\d.]+)/"
      },
      "download": {
        "fileName": "ZoomInstallerFull-{version}-x64.msi"
      },
      "installer": {
        "type": "msi",
        "silentArgs": "/qn /norestart",
        "interactiveArgs": ""
      }
    },
    {
      "id": "teams",
      "name": "Microsoft Teams (new)",
      "category": "Communication",
      "notes": "Uses Microsoft's bootstrapper to provision Teams for all users. Needs admin. Microsoft has no public 'latest version' feed, so the script can't compare versions for Teams.",
      "detect": {
        "appx": "MSTeams"
      },
      "latest": {
        "type": "none"
      },
      "download": {
        "url": "https://go.microsoft.com/fwlink/?linkid=2243204&clcid=0x409",
        "fileName": "teamsbootstrapper.exe"
      },
      "installer": {
        "type": "exe",
        "silentArgs": "-p",
        "interactiveArgs": "-p"
      }
    },
    {
      "id": "slack",
      "name": "Slack",
      "category": "Communication",
      "perUser": true,
      "notes": "Per-user install. Run as the logged-in user; skipped under SYSTEM unless named explicitly.",
      "detect": {
        "displayName": "^Slack$"
      },
      "latest": {
        "type": "redirect",
        "url": "https://slack.com/ssb/download-win64",
        "regex": "/(?<version>\\d+\\.\\d+\\.\\d+)/"
      },
      "download": {
        "fileName": "SlackSetup-{version}.exe"
      },
      "installer": {
        "type": "exe",
        "silentArgs": "-s",
        "interactiveArgs": ""
      }
    },
    {
      "id": "7zip",
      "name": "7-Zip",
      "category": "Utilities",
      "detect": {
        "displayName": "^7-Zip"
      },
      "latest": {
        "type": "github",
        "repo": "ip7z/7zip",
        "assetRegex": "^7z\\d+-x64\\.msi$"
      },
      "installer": {
        "type": "msi",
        "silentArgs": "/qn /norestart",
        "interactiveArgs": ""
      }
    },
    {
      "id": "notepadplusplus",
      "name": "Notepad++",
      "category": "Utilities",
      "detect": {
        "displayName": "^Notepad\\+\\+"
      },
      "latest": {
        "type": "github",
        "repo": "notepad-plus-plus/notepad-plus-plus",
        "assetRegex": "^npp\\.[\\d.]+\\.Installer\\.x64\\.exe$"
      },
      "installer": {
        "type": "exe",
        "silentArgs": "/S",
        "interactiveArgs": ""
      }
    },
    {
      "id": "vlc",
      "name": "VLC media player",
      "category": "Utilities",
      "detect": {
        "displayName": "^VLC media player"
      },
      "latest": {
        "type": "regex",
        "url": "https://www.videolan.org/vlc/download-windows.html",
        "regex": "vlc-(?<version>\\d+\\.\\d+\\.\\d+)-win64\\.msi"
      },
      "download": {
        "url": "https://get.videolan.org/vlc/{version}/win64/vlc-{version}-win64.msi"
      },
      "installer": {
        "type": "msi",
        "silentArgs": "/qn /norestart",
        "interactiveArgs": ""
      }
    },
    {
      "id": "adobereader",
      "name": "Adobe Acrobat Reader",
      "category": "Utilities",
      "notes": "64-bit Reader registers as 'Adobe Acrobat (64-bit)', the same name as Acrobat Pro - don't run this on machines with Pro.",
      "detect": {
        "displayName": "^Adobe Acrobat( Reader)?( DC)?( \\(64-bit\\))?$"
      },
      "latest": {
        "type": "json",
        "url": "https://rdc.adobe.io/reader/products?lang=en&site=enterprise&os=Windows%2011&api_key=dc-get-adobereader-cdn",
        "path": "products.reader[0].version"
      },
      "download": {
        "url": "https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/{versionNoDots}/AcroRdrDCx64{versionNoDots}_en_US.exe"
      },
      "installer": {
        "type": "exe",
        "silentArgs": "/sAll /rs /msi EULA_ACCEPT=YES",
        "interactiveArgs": ""
      }
    },
    {
      "id": "everything",
      "name": "Everything (voidtools)",
      "category": "Utilities",
      "detect": {
        "displayName": "^Everything"
      },
      "latest": {
        "type": "regex",
        "url": "https://www.voidtools.com/downloads/",
        "regex": "Everything-(?<version>\\d+\\.\\d+\\.\\d+\\.\\d+)\\.x64\\.msi"
      },
      "download": {
        "url": "https://www.voidtools.com/Everything-{version}.x64.msi"
      },
      "installer": {
        "type": "msi",
        "silentArgs": "/qn /norestart",
        "interactiveArgs": ""
      }
    },
    {
      "id": "sharex",
      "name": "ShareX",
      "category": "Utilities",
      "detect": {
        "displayName": "^ShareX"
      },
      "latest": {
        "type": "github",
        "repo": "ShareX/ShareX",
        "assetRegex": "^ShareX-[\\d.]+-setup(-x64)?\\.exe$"
      },
      "installer": {
        "type": "exe",
        "silentArgs": "/VERYSILENT /NORESTART /NORUN",
        "interactiveArgs": ""
      }
    }
  ]
}
'@
#endregion embedded

# ----- Settings -----------------------------------------------------------------------
# Only used when there is no embedded list and no apps.json nearby (e.g. running
# src\engine.ps1 on its own).
$DefaultManifestUrl = 'https://raw.githubusercontent.com/Spot-Thorn/kura-apps/main/apps.json'
$UserAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36'
# --------------------------------------------------------------------------------------

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'   # makes Invoke-WebRequest much faster on PS 5.1
try {
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
    [Net.ServicePointManager]::DefaultConnectionLimit = 16
} catch { }

# True when a 32-bit PowerShell (common with RMM agents) runs on 64-bit Windows.
$Is32On64 = [Environment]::Is64BitOperatingSystem -and -not [Environment]::Is64BitProcess
$IsSystem = $false
try { $IsSystem = [Security.Principal.WindowsIdentity]::GetCurrent().IsSystem } catch { $IsSystem = $false }

# ----- Logging ------------------------------------------------------------------------
$LogDir = $null
foreach ($root in @($env:ProgramData, [IO.Path]::GetTempPath())) {
    if (-not $root) { continue }
    try {
        $dir = Join-Path $root (Join-Path 'KuraApps' 'Logs')
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        $LogDir = $dir
        break
    } catch { $LogDir = $null }
}
if (-not $LogDir) { $LogDir = [IO.Path]::GetTempPath() }
$LogFile = Join-Path $LogDir ("Install-Apps_{0}.log" -f (Get-Date -Format 'yyyyMMdd'))

function Write-KuraLog {
    param(
        [string]$Message,
        [ValidateSet('Info', 'Ok', 'Warn', 'Error')][string]$Level = 'Info',
        [switch]$Quiet
    )
    $line = '{0} [{1}] {2}' -f (Get-Date -Format 's'), $Level.ToUpper(), $Message
    try { Add-Content -Path $LogFile -Value $line } catch { }
    if (-not $Quiet) {
        $color = @{ Info = 'Gray'; Ok = 'Green'; Warn = 'Yellow'; Error = 'Red' }[$Level]
        Write-Host $Message -ForegroundColor $color
    }
}

# Innermost exception message (drops "Exception calling GetResponse..." wrappers)
function Get-ErrorText {
    param($ErrorRecord)
    $e = $ErrorRecord.Exception
    while ($e.InnerException) { $e = $e.InnerException }
    return $e.Message
}

# ----- Version helpers ----------------------------------------------------------------
function ConvertTo-VersionParts {
    param([string]$Version)
    if (-not $Version) { return $null }
    $m = [regex]::Match($Version, '\d+(?:[.,]\d+)*')
    if (-not $m.Success) { return $null }
    $parts = foreach ($p in ($m.Value -split '[.,]')) { if ($p.Length -gt 18) { [int64]::MaxValue } else { [int64]$p } }
    return , ([int64[]]@($parts))
}

# Returns -1 (a older), 0 (same), 1 (a newer), or $null when either can't be parsed.
# Missing parts count as 0, so 26.03 == 26.03.00.0.
function Compare-AppVersion {
    param([string]$A, [string]$B)
    $pa = ConvertTo-VersionParts $A
    $pb = ConvertTo-VersionParts $B
    if ($null -eq $pa -or $null -eq $pb) { return $null }
    $n = [Math]::Max($pa.Count, $pb.Count)
    for ($i = 0; $i -lt $n; $i++) {
        $x = 0; if ($i -lt $pa.Count) { $x = $pa[$i] }
        $y = 0; if ($i -lt $pb.Count) { $y = $pb[$i] }
        if ($x -lt $y) { return -1 }
        if ($x -gt $y) { return 1 }
    }
    return 0
}

# Optional per-app rewrite of a version before comparing ("compare": { "latest": {pattern, replace}, "installed": {...} })
function Get-CompareVersion {
    param($AppDef, [string]$Version, [string]$Which)
    if (-not $Version -or -not $AppDef.compare) { return $Version }
    $rule = $AppDef.compare.$Which
    if (-not $rule) { return $Version }
    try { return [regex]::Replace($Version, [string]$rule.pattern, [string]$rule.replace) }
    catch { return $Version }
}

# ----- Manifest -----------------------------------------------------------------------
function Get-Manifest {
    param([string]$Source)
    if (-not $Source -and $EmbeddedManifest) {
        Write-KuraLog 'Using the embedded app list' -Quiet
        return ($EmbeddedManifest | ConvertFrom-Json)
    }
    if (-not $Source) {
        # Engine run from a clone of the repo (src\engine.ps1): use the repo's apps.json.
        $Source = $DefaultManifestUrl
        if ($PSScriptRoot) {
            foreach ($candidate in @((Join-Path $PSScriptRoot 'apps.json'), (Join-Path (Split-Path $PSScriptRoot -Parent) 'apps.json'))) {
                if (Test-Path -LiteralPath $candidate) { $Source = $candidate; break }
            }
        }
    }
    Write-KuraLog "Loading app list from $Source" -Quiet
    if ($Source -match '^https?://') {
        $raw = Invoke-RestMethod -Uri $Source -UseBasicParsing -UserAgent $UserAgent -Headers @{ 'Cache-Control' = 'no-cache' }
        if ($raw -is [string]) { $data = $raw.TrimStart([char]0xFEFF) | ConvertFrom-Json } else { $data = $raw }
    } else {
        $data = Get-Content -LiteralPath $Source -Raw | ConvertFrom-Json
    }
    if (-not $data.apps) { throw "No 'apps' found in manifest $Source" }
    return $data
}

# ----- Installed version detection ----------------------------------------------------
# Reads Add/Remove Programs entries from the 64-bit and 32-bit registry views plus the
# current user, so detection is correct even from a 32-bit PowerShell host.
$script:UninstallCache = $null
function Get-UninstallEntries {
    if ($null -ne $script:UninstallCache) { return $script:UninstallCache }
    $list = New-Object System.Collections.Generic.List[object]
    $sub = 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'
    $views = @(
        @([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry64),
        @([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry32),
        @([Microsoft.Win32.RegistryHive]::CurrentUser, [Microsoft.Win32.RegistryView]::Default)
    )
    foreach ($v in $views) {
        try {
            $base = [Microsoft.Win32.RegistryKey]::OpenBaseKey($v[0], $v[1])
            $key = $base.OpenSubKey($sub)
            if ($key) {
                foreach ($name in $key.GetSubKeyNames()) {
                    try {
                        $k = $key.OpenSubKey($name)
                        if ($k) {
                            $list.Add([pscustomobject]@{
                                DisplayName    = [string]$k.GetValue('DisplayName')
                                DisplayVersion = [string]$k.GetValue('DisplayVersion')
                            })
                            $k.Close()
                        }
                    } catch { }
                }
                $key.Close()
            }
            $base.Close()
        } catch { }
    }
    $script:UninstallCache = $list
    return $list
}

function Expand-AppPath {
    param([string]$Path)
    # In 32-bit PowerShell on 64-bit Windows, %ProgramFiles% points at "Program Files (x86)".
    if ($Is32On64 -and $env:ProgramW6432) { $Path = $Path -replace '%ProgramFiles%', $env:ProgramW6432.Replace('$', '$$') }
    return [Environment]::ExpandEnvironmentVariables($Path)
}

function Get-InstalledVersion {
    param($AppDef)
    $d = $AppDef.detect
    if (-not $d) { return $null }

    # 1) File version of a known exe (most reliable - always 4 numeric parts)
    foreach ($f in @($d.files)) {
        if (-not $f) { continue }
        $path = Expand-AppPath $f
        if (Test-Path -LiteralPath $path) {
            $vi = (Get-Item -LiteralPath $path).VersionInfo
            return '{0}.{1}.{2}.{3}' -f $vi.FileMajorPart, $vi.FileMinorPart, $vi.FileBuildPart, $vi.FilePrivatePart
        }
    }

    # 2) Store/MSIX package (e.g. new Teams)
    if ($d.appx) {
        if ($PSVersionTable.PSEdition -eq 'Core' -and -not (Get-Module Appx)) {
            try { Import-Module Appx -UseWindowsPowerShell -ErrorAction Stop -WarningAction SilentlyContinue } catch { }
        }
        $pkg = $null
        try { $pkg = Get-AppxPackage -Name $d.appx -AllUsers -ErrorAction Stop }
        catch { try { $pkg = Get-AppxPackage -Name $d.appx -ErrorAction Stop } catch { } }
        if (-not $pkg) {
            try { $pkg = Get-AppxProvisionedPackage -Online -ErrorAction Stop | Where-Object { $_.DisplayName -eq $d.appx } } catch { }
        }
        if ($pkg) {
            $best = $null
            foreach ($p in @($pkg)) {
                if (-not $best -or (Compare-AppVersion ([string]$p.Version) $best) -gt 0) { $best = [string]$p.Version }
            }
            if ($best) { return $best }
        }
    }

    # 3) Add/Remove Programs entry (regex on DisplayName, case-insensitive)
    if ($d.displayName) {
        $best = $null
        foreach ($h in (Get-UninstallEntries)) {
            if (-not $h.DisplayName -or -not $h.DisplayVersion) { continue }
            if ($h.DisplayName -notmatch $d.displayName) { continue }
            if (-not $best -or (Compare-AppVersion $h.DisplayVersion $best) -gt 0) { $best = $h.DisplayVersion }
        }
        return $best
    }
    return $null
}

# ----- Latest version resolution ------------------------------------------------------
function Get-JsonPath {
    param($Object, [string]$Path)
    foreach ($seg in ($Path -split '\.')) {
        if ($seg -notmatch '^(?<name>[^\[]*)(?<idx>(\[\d+\])*)$') { throw "Bad json path segment '$seg'" }
        $name = $Matches['name']; $idx = $Matches['idx']
        if ($name) { $Object = $Object.$name }
        foreach ($i in [regex]::Matches($idx, '\d+')) { $Object = @($Object)[[int]$i.Value] }
    }
    return $Object
}

# Follows redirects and returns the final URL without downloading the file.
function Get-RedirectTarget {
    param([string]$Url)
    foreach ($method in 'HEAD', 'GET') {
        $req = [System.Net.HttpWebRequest]::Create($Url)
        $req.Method = $method
        $req.AllowAutoRedirect = $true
        $req.UserAgent = $UserAgent
        $req.Timeout = 30000
        try {
            $resp = $req.GetResponse()
            $final = $resp.ResponseUri.AbsoluteUri
            try { $req.Abort() } catch { }
            try { $resp.Close() } catch { }
            return $final
        } catch {
            # Close any error response so the connection isn't left hanging
            try { $_.Exception.InnerException.Response.Close() } catch { }
            try { $_.Exception.Response.Close() } catch { }
            if ($method -eq 'GET') { throw }
        }
    }
}

# Latest GitHub release: version + download URL of the asset matching $AssetRegex.
# Uses the API (set $env:GITHUB_TOKEN to lift the 60 requests/hour limit). If the API
# refuses (rate limit), falls back to the normal release web pages.
function Get-GitHubLatest {
    param([string]$Repo, [string]$AssetRegex)
    try {
        $headers = @{ Accept = 'application/vnd.github+json' }
        if ($env:GITHUB_TOKEN) { $headers.Authorization = "Bearer $env:GITHUB_TOKEN" }
        $rel = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest" -UseBasicParsing -UserAgent $UserAgent -Headers $headers
        $asset = @($rel.assets) | Where-Object { $_.name -match $AssetRegex } | Select-Object -First 1
        if (-not $asset) { throw "No release asset matching '$AssetRegex' in $Repo $($rel.tag_name)" }
        return @{ Tag = [string]$rel.tag_name; Url = [string]$asset.browser_download_url }
    } catch {
        $apiError = $_.Exception.Message
        Write-KuraLog "[$Repo] GitHub API failed ($apiError) - trying release page" -Level Warn -Quiet
    }
    $final = Get-RedirectTarget "https://github.com/$Repo/releases/latest"
    if ($final -notmatch '/releases/tag/(?<tag>[^/?#]+)') { throw "GitHub API failed ($apiError) and release page gave no tag" }
    $tag = [Uri]::UnescapeDataString($Matches['tag'])
    $html = (Invoke-WebRequest -Uri "https://github.com/$Repo/releases/expanded_assets/$tag" -UseBasicParsing -UserAgent $UserAgent).Content
    foreach ($m in [regex]::Matches($html, 'href="(?<href>/[^"]+/releases/download/[^"]+)"')) {
        $href = $m.Groups['href'].Value
        $name = [Uri]::UnescapeDataString(($href -split '/')[-1])
        if ($name -match $AssetRegex) { return @{ Tag = $tag; Url = "https://github.com$href" } }
    }
    throw "No release asset matching '$AssetRegex' in $Repo $tag"
}

function Expand-Template {
    param([string]$Template, [string]$Version)
    if (-not $Template) { return $Template }
    $v = $Version
    if (-not $v) { $v = 'latest' }
    return $Template.Replace('{versionNoDots}', ($v -replace '\.', '')).Replace('{version}', $v)
}

function Resolve-Latest {
    param($AppDef)
    $l = $AppDef.latest
    $version = $null; $url = $null; $err = $null
    $ic = [System.Text.RegularExpressions.RegexOptions]::IgnoreCase

    try {
        switch ($l.type) {
            'json' {
                $data = Invoke-RestMethod -Uri $l.url -UseBasicParsing -UserAgent $UserAgent
                $version = [string](Get-JsonPath $data $l.path)
            }
            'redirect' {
                $url = Get-RedirectTarget $l.url
                $m = [regex]::Match($url, $l.regex, $ic)
                if ($m.Success) { $version = $m.Groups['version'].Value }
            }
            'regex' {
                $html = (Invoke-WebRequest -Uri $l.url -UseBasicParsing -UserAgent $UserAgent).Content
                $m = [regex]::Match($html, $l.regex, $ic)
                if ($m.Success) {
                    $version = $m.Groups['version'].Value
                    if ($m.Groups['url'].Success) { $url = ([Uri]::new([Uri]$l.url, $m.Groups['url'].Value)).AbsoluteUri }
                }
            }
            'github' {
                $gh = Get-GitHubLatest -Repo $l.repo -AssetRegex $l.assetRegex
                $version = $gh.Tag -replace '^[^\d]*', ''
                $url = $gh.Url
            }
            'script' {
                $code = (@($l.script) -join "`n")
                $r = & ([scriptblock]::Create($code))
                $version = [string]$r.Version
                $url = [string]$r.Url
            }
            'none' { }
            default { throw "Unknown latest.type '$($l.type)'" }
        }
        if ($l.type -ne 'none' -and -not $version) { throw 'Could not find a version number in the response' }
    } catch {
        $err = Get-ErrorText $_
        $version = $null
    }

    # A download.url in the manifest wins. Templates with {version} need a resolved version.
    if ($AppDef.download -and $AppDef.download.url) {
        $t = [string]$AppDef.download.url
        if ($version -or $t -notmatch '\{version') { $url = Expand-Template $t $version } else { $url = $null }
    }

    if ($url) {
        $u = $null
        if (-not [Uri]::TryCreate($url, [UriKind]::Absolute, [ref]$u)) { $err = "Download URL is not absolute: $url"; $url = $null }
    }

    $fileName = $null
    if ($AppDef.download -and $AppDef.download.fileName) {
        $fileName = Expand-Template ([string]$AppDef.download.fileName) $version
    } elseif ($url) {
        $leaf = [IO.Path]::GetFileName(([Uri]$url).AbsolutePath)
        if ($leaf -match '\.(msi|exe|msix|msixbundle)$') { $fileName = $leaf }
    }
    if (-not $fileName) { $fileName = '{0}-{1}.{2}' -f $AppDef.id, $(if ($version) { $version } else { 'latest' }), $AppDef.installer.type }
    $fileName = $fileName -replace '[\\/:*?"<>|]', '_'

    return [pscustomobject]@{ Version = $version; Url = $url; FileName = $fileName; Error = $err }
}

# ----- State for one app --------------------------------------------------------------
function Get-AppState {
    param($AppDef, $Latest)
    if (-not $Latest) { $Latest = Resolve-Latest $AppDef }
    $installed = $null
    try { $installed = Get-InstalledVersion $AppDef } catch { Write-KuraLog "[$($AppDef.id)] detection failed: $($_.Exception.Message)" -Level Warn -Quiet }

    $cmp = $null
    if ($installed -and $Latest.Version) {
        try { $cmp = Compare-AppVersion (Get-CompareVersion $AppDef $installed 'installed') (Get-CompareVersion $AppDef $Latest.Version 'latest') }
        catch { $cmp = $null }
    }
    $status =
        if (-not $installed) { 'Not installed' }
        elseif ($null -eq $cmp) { 'Installed' }
        elseif ($cmp -lt 0) { 'Update available' }
        else { 'Up to date' }

    return [pscustomobject]@{
        Def       = $AppDef
        Installed = $installed
        Latest    = $Latest
        Compare   = $cmp
        Status    = $status
    }
}

# ----- Download + install -------------------------------------------------------------
function Test-IsAdmin {
    try {
        $id = [Security.Principal.WindowsIdentity]::GetCurrent()
        return ([Security.Principal.WindowsPrincipal]$id).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    } catch { return $false }
}

function Test-Signature {
    param([string]$File, [bool]$CanPrompt)
    if ($SkipSignatureCheck) { return $true }
    $sig = Get-AuthenticodeSignature -FilePath $File
    if ($sig.Status -eq 'Valid') {
        Write-KuraLog "  Signed by: $($sig.SignerCertificate.Subject)" -Quiet
        return $true
    }
    Write-KuraLog "  Signature check: $($sig.Status) ($($sig.StatusMessage))" -Level Warn
    if (-not $CanPrompt) { return $false }
    $c = Read-Choice -Title 'Unsigned installer' -Message "Run it anyway?" -Options @('&No', '&Yes') -Default 0
    return ($c -eq 1)
}

function Invoke-Installer {
    param([string]$Exe, [string]$Arguments, [string]$Id, [string]$InstallMode)
    $Arguments = $Arguments.Trim()
    Write-KuraLog "[$Id] Installing ($InstallMode): $Exe $Arguments"
    if ($Arguments) { $p = Start-Process -FilePath $Exe -ArgumentList $Arguments -PassThru }
    else { $p = Start-Process -FilePath $Exe -PassThru }
    $null = $p.Handle          # needed on PS 5.1 so ExitCode is populated
    $p.WaitForExit()           # waits for the installer only, not the app it launches afterwards
    return $p.ExitCode
}

function Install-AppPackage {
    param($State, [ValidateSet('Silent', 'Interactive')][string]$InstallMode, [bool]$CanPrompt, [bool]$Reinstall = $false)
    $def = $State.Def
    $latest = $State.Latest
    $script:UninstallCache = $null
    if (-not $latest.Url) {
        Write-KuraLog "[$($def.id)] No download URL (latest version lookup failed: $($latest.Error))" -Level Error
        return $false
    }

    $file = Join-Path $DownloadPath $latest.FileName
    try {
        New-Item -ItemType Directory -Path $DownloadPath -Force | Out-Null
        Write-KuraLog "[$($def.id)] Downloading $($latest.Url)"
        Invoke-WebRequest -Uri $latest.Url -OutFile $file -UseBasicParsing -UserAgent $UserAgent
        if (-not (Test-Path -LiteralPath $file) -or (Get-Item -LiteralPath $file).Length -lt 10KB) { throw 'Download is missing or too small' }
    } catch {
        Write-KuraLog "[$($def.id)] Download failed: $($_.Exception.Message)" -Level Error
        Remove-Item -LiteralPath $file -Force -ErrorAction SilentlyContinue
        return $false
    }

    $sigOk = $false
    try { $sigOk = Test-Signature -File $file -CanPrompt $CanPrompt }
    catch { Write-KuraLog "[$($def.id)] Signature check failed: $($_.Exception.Message)" -Level Error }
    if (-not $sigOk) {
        Write-KuraLog "[$($def.id)] Skipped - installer signature not valid" -Level Error
        if (-not $KeepDownloads) { Remove-Item -LiteralPath $file -Force -ErrorAction SilentlyContinue }
        return $false
    }

    $userArgs = if ($InstallMode -eq 'Silent') { [string]$def.installer.silentArgs } else { [string]$def.installer.interactiveArgs }
    try {
        switch ($def.installer.type) {
            'msi' {
                $exe = "$env:SystemRoot\System32\msiexec.exe"
                $msiLog = Join-Path $LogDir ("{0}_{1}.msi.log" -f $def.id, (Get-Date -Format 'yyyyMMdd-HHmmss'))
                $base = ('/i "{0}" {1} /l*v "{2}"' -f $file, $userArgs, $msiLog)
                if ($Reinstall) {
                    # Same-version MSI: plain /i only runs maintenance mode and changes nothing, so force a real reinstall
                    $code = Invoke-Installer -Exe $exe -Arguments "$base REINSTALL=ALL REINSTALLMODE=vomus" -Id $def.id -InstallMode $InstallMode
                    # 1605 = this exact MSI isn't installed (e.g. app came from an EXE or auto-updated) - do a normal install
                    if ($code -eq 1605) { $code = Invoke-Installer -Exe $exe -Arguments $base -Id $def.id -InstallMode $InstallMode }
                } else {
                    $code = Invoke-Installer -Exe $exe -Arguments $base -Id $def.id -InstallMode $InstallMode
                }
            }
            'exe' { $code = Invoke-Installer -Exe $file -Arguments $userArgs -Id $def.id -InstallMode $InstallMode }
            default { Write-KuraLog "[$($def.id)] Unknown installer.type '$($def.installer.type)'" -Level Error; return $false }
        }
    } catch {
        Write-KuraLog "[$($def.id)] Failed to start installer: $($_.Exception.Message)" -Level Error
        return $false
    } finally {
        if (-not $KeepDownloads) { Remove-Item -LiteralPath $file -Force -ErrorAction SilentlyContinue }
    }

    switch ($code) {
        0 { Write-KuraLog "[$($def.id)] Installed OK" -Level Ok; return $true }
        3010 { Write-KuraLog "[$($def.id)] Installed OK - reboot required" -Level Ok; return $true }
        1641 { Write-KuraLog "[$($def.id)] Installed OK - installer started a reboot" -Level Ok; return $true }
        1602 { Write-KuraLog "[$($def.id)] Cancelled by user (1602)" -Level Warn; return $false }
        1638 { Write-KuraLog "[$($def.id)] This version (or a newer one) is already installed (1638)" -Level Ok; return $true }
        1618 { Write-KuraLog "[$($def.id)] Another install is already running (1618). Try again in a few minutes." -Level Error; return $false }
        default { Write-KuraLog "[$($def.id)] Installer exited with code $code" -Level Error; return $false }
    }
}

# ----- UI -----------------------------------------------------------------------------
function Read-Choice {
    param([string]$Title, [string]$Message, [string[]]$Options, [int]$Default = 0)
    $choices = [System.Management.Automation.Host.ChoiceDescription[]]@(
        $Options | ForEach-Object { New-Object System.Management.Automation.Host.ChoiceDescription $_ }
    )
    return $Host.UI.PromptForChoice($Title, $Message, $choices, $Default)
}

function Show-Table {
    param([object[]]$States)
    $fmt = ' {0,3}  {1,-14} {2,-24} {3,-17} {4,-17} {5}'
    Write-Host ''
    Write-Host ($fmt -f '#', 'Category', 'App', 'Installed', 'Latest', 'Status') -ForegroundColor Cyan
    Write-Host (' ' + ('-' * 95)) -ForegroundColor DarkGray
    $i = 0
    foreach ($s in $States) {
        $i++
        $latestText = if ($s.Latest.Version) { $s.Latest.Version } elseif ($s.Def.latest.type -eq 'none') { 'n/a' } else { 'lookup failed' }
        $color = switch ($s.Status) {
            'Up to date' { 'Green' }
            'Update available' { 'Yellow' }
            'Installed' { 'Gray' }
            default { 'White' }
        }
        $inst = if ($s.Installed) { $s.Installed } else { '-' }
        Write-Host ($fmt -f $i, $s.Def.category, $s.Def.name, $inst, $latestText, $s.Status) -ForegroundColor $color
    }
    Write-Host ''
}

# Turns "1,3,5-7", "all", "updates", "browsers", "chrome" into a list of indexes (0-based).
function Resolve-Selection {
    param([string]$Text, [object[]]$States)
    $picked = New-Object System.Collections.Generic.List[int]
    $Text = $Text -replace '\s*-\s*', '-'
    foreach ($tok in ($Text -split '[,\s]+' | Where-Object { $_ })) {
        if ($tok -match '^(\d+)-(\d+)$') {
            foreach ($n in ([int]$Matches[1])..([int]$Matches[2])) { if ($n -ge 1 -and $n -le $States.Count) { $picked.Add($n - 1) } }
        } elseif ($tok -match '^\d+$') {
            $n = [int]$tok; if ($n -ge 1 -and $n -le $States.Count) { $picked.Add($n - 1) }
        } else {
            for ($i = 0; $i -lt $States.Count; $i++) {
                $s = $States[$i]
                if ($tok -eq 'all' -or
                    ($tok -eq 'updates' -and $s.Status -eq 'Update available') -or
                    $s.Def.id -eq $tok -or $s.Def.category -eq $tok) { $picked.Add($i) }
            }
        }
    }
    return @($picked | Select-Object -Unique)
}

function Invoke-InteractiveInstall {
    param($State)
    $def = $State.Def
    Write-Host ''
    Write-Host "== $($def.name) ==" -ForegroundColor Cyan
    if ($def.notes) { Write-Host "   Note: $($def.notes)" -ForegroundColor DarkGray }
    if ($State.Latest.Error) { Write-Host "   Latest version lookup failed: $($State.Latest.Error)" -ForegroundColor Yellow }

    $installed = if ($State.Installed) { $State.Installed } else { 'not installed' }
    $latest = if ($State.Latest.Version) { $State.Latest.Version } else { 'unknown' }

    if ($def.perUser -and $IsSystem) {
        Write-Host '   This app installs per-user. Running as SYSTEM will put it in the system profile, not a real user.' -ForegroundColor Yellow
    }
    Write-Host "   Installed: $installed   Latest: $latest"
    if ($State.Status -eq 'Up to date') {
        Write-Host '   Already on the latest version.' -ForegroundColor Green
        $c = Read-Choice -Title '' -Message 'Reinstall?' -Options @('&Reinstall silently', 'Reinstall &interactively', '&Cancel') -Default 2
    } else {
        $c = Read-Choice -Title '' -Message 'Install?' -Options @('&Silent install', '&Interactive install', '&Cancel') -Default 0
    }
    $reinstall = ($State.Compare -eq 0)
    switch ($c) {
        0 { $ok = Install-AppPackage -State $State -InstallMode Silent -CanPrompt $true -Reinstall $reinstall }
        1 { $ok = Install-AppPackage -State $State -InstallMode Interactive -CanPrompt $true -Reinstall $reinstall }
        default { Write-KuraLog "[$($def.id)] Cancelled" -Level Info; return }
    }
    if ($ok) {
        $now = $null
        try { $now = Get-InstalledVersion $def } catch { }
        if ($now) { Write-KuraLog "[$($def.id)] Now reporting version $now" -Level Ok }
    }
}

# ----- Main ---------------------------------------------------------------------------
Write-KuraLog "=== Install-Apps started by $env:USERDOMAIN\$env:USERNAME on $env:COMPUTERNAME ===" -Quiet
try {
    $data = Get-Manifest $Manifest
} catch {
    Write-KuraLog "Could not load the app list: $($_.Exception.Message)" -Level Error
    Write-KuraLog 'Check the internet connection, or pass -Manifest <path or URL to apps.json>.' -Level Error
    # In the interactive menu (e.g. inside Kura) keep the window open so the error can be read
    if (-not $App -and -not $CheckFeeds -and -not $List -and -not $Unattended) { Read-Host -Prompt 'Press Enter to exit' | Out-Null }
    exit 2
}
$defs = @($data.apps)
if ($EmbeddedAppId) {
    $defs = @($defs | Where-Object { $_.id -eq $EmbeddedAppId })
    if (-not $defs.Count) { Write-KuraLog "App '$EmbeddedAppId' is not in the app list" -Level Error; exit 2 }
    if ($Unattended -and -not $App) { $App = @($EmbeddedAppId) }
} elseif ($Unattended -and -not $App) {
    Write-KuraLog '-Unattended is for single-app scripts. Here, use -App <ids>, -App updates or -App all.' -Level Error
    exit 2
}

function Get-AllStates {
    param([object[]]$Defs, [object[]]$Previous)
    $script:UninstallCache = $null
    $out = @()
    for ($i = 0; $i -lt $Defs.Count; $i++) {
        $d = $Defs[$i]
        $cached = $null
        if ($Previous) { $cached = $Previous[$i].Latest }
        if (-not $cached) { Write-Host ("  checking {0}..." -f $d.name) -ForegroundColor DarkGray }
        $out += Get-AppState -AppDef $d -Latest $cached
    }
    return $out
}

# --- Feed check (CI) ---
if ($CheckFeeds) {
    $bad = 0
    foreach ($d in $defs) {
        $r = Resolve-Latest $d
        $state = 'OK'
        if ($d.latest.type -ne 'none' -and -not $r.Version) { $state = "FAIL: $($r.Error)" }
        elseif (-not $r.Url) { $state = "FAIL: no download URL $($r.Error)" }
        else {
            try { $null = Get-RedirectTarget $r.Url } catch { $state = "FAIL: download URL - $(Get-ErrorText $_)" }
        }
        if ($state -ne 'OK') { $bad++ }
        $v = if ($r.Version) { $r.Version } else { '-' }
        $line = '{0,-16} {1,-18} {2}' -f $d.id, $v, $state
        if ($state -eq 'OK') { Write-Host $line -ForegroundColor Green; Write-Host "                 $($r.Url)" -ForegroundColor DarkGray }
        else { Write-Host $line -ForegroundColor Red }
    }
    Write-Host ''
    Write-Host ("{0} of {1} app feeds OK" -f ($defs.Count - $bad), $defs.Count)
    exit ([int]($bad -gt 0))
}

# --- Unattended ---
if ($App) {
    $targets = @()
    $wanted = @($App | ForEach-Object { $_ -split ',' } | ForEach-Object { $_.Trim() } | Where-Object { $_ })
    foreach ($d in $defs) {
        if ($wanted -contains 'all' -or $wanted -contains 'updates' -or $wanted -contains $d.id) { $targets += $d }
    }
    $unknown = @($wanted | Where-Object { $_ -notin @('all', 'updates') -and $_ -notin $defs.id })
    foreach ($u in $unknown) { Write-KuraLog "Unknown app id '$u' (use -List to see ids)" -Level Warn }
    if (-not (Test-IsAdmin)) { Write-KuraLog 'Not running as administrator - machine-wide installs will probably fail.' -Level Warn }

    $failed = $unknown.Count
    foreach ($d in $targets) {
        try {
            $named = $wanted -contains $d.id
            # Per-user apps (Discord, Slack) under SYSTEM land in the system profile - only do it if asked by name
            if ($d.perUser -and $IsSystem -and -not $named) {
                Write-KuraLog "[$($d.id)] Per-user app and running as SYSTEM - skipping (name it explicitly to force)" -Level Warn
                continue
            }
            $s = Get-AppState -AppDef $d
            if ($wanted -contains 'updates' -and -not ($wanted -contains 'all') -and -not $named -and $s.Status -ne 'Update available') { continue }
            if (-not $Force -and $s.Status -eq 'Up to date') {
                Write-KuraLog "[$($d.id)] Already current ($($s.Installed)) - skipping"
                continue
            }
            if (-not $Force -and $s.Status -eq 'Installed') {
                Write-KuraLog "[$($d.id)] Installed ($($s.Installed)) but can't compare to latest ($($s.Latest.Version)) - skipping (use -Force to reinstall)"
                continue
            }
            $reinstall = ($s.Compare -eq 0)
            if (-not (Install-AppPackage -State $s -InstallMode $Mode -CanPrompt $false -Reinstall $reinstall)) { $failed++ }
        } catch {
            Write-KuraLog "[$($d.id)] Unexpected error: $($_.Exception.Message)" -Level Error
            $failed++
        }
    }
    Write-KuraLog "=== Done. $failed failure(s). Log: $LogFile ===" -Quiet
    exit ([int]($failed -gt 0))
}

# --- Single app (scripts\install-<id>.ps1) ---
if ($EmbeddedAppId -and -not $List) {
    $def = $defs[0]
    Write-Host "Checking $($def.name)..." -ForegroundColor Cyan
    $single = Get-AppState -AppDef $def
    Show-Table @($single)
    if (-not $def.perUser -and -not (Test-IsAdmin)) {
        Write-KuraLog 'Not running as administrator - this install will probably fail.' -Level Warn
    }
    try { Invoke-InteractiveInstall -State $single }
    catch { Write-KuraLog "[$($def.id)] Unexpected error: $($_.Exception.Message)" -Level Error }
    Write-Host ''
    Write-Host "Log: $LogFile" -ForegroundColor DarkGray
    Read-Host -Prompt 'Press Enter to exit' | Out-Null
    return
}

# --- List only ---
Write-Host 'Checking installed and latest versions...' -ForegroundColor Cyan
$states = @(Get-AllStates -Defs $defs)
if ($List) {
    Show-Table $states
    Write-Host 'App ids: ' -NoNewline; Write-Host ($defs.id -join ', ')
    return
}

# --- Interactive menu ---
if (-not (Test-IsAdmin)) {
    Write-KuraLog 'Not running as administrator. Per-user apps (Discord, Slack) are fine; most others need admin.' -Level Warn
}
while ($true) {
    Show-Table $states
    Write-Host 'Pick apps: numbers (1,3,5-7), a category (Browsers), an id (chrome), ' -NoNewline
    Write-Host 'all' -ForegroundColor Cyan -NoNewline; Write-Host ', ' -NoNewline
    Write-Host 'updates' -ForegroundColor Cyan -NoNewline; Write-Host ', ' -NoNewline
    Write-Host 'r' -ForegroundColor Cyan -NoNewline; Write-Host ' to re-check, or ' -NoNewline
    Write-Host 'q' -ForegroundColor Cyan -NoNewline; Write-Host ' to quit.'
    $answer = Read-Host 'Selection'
    if (-not $answer) { continue }
    if ($answer -match '^\s*q(uit)?\s*$') { break }
    if ($answer -match '^\s*r\s*$') {
        $states = @(Get-AllStates -Defs $defs)
        continue
    }
    $idx = @(Resolve-Selection -Text $answer -States $states)
    if (-not $idx.Count) { Write-Host 'Nothing matched that selection.' -ForegroundColor Yellow; continue }
    foreach ($i in $idx) {
        try { Invoke-InteractiveInstall -State $states[$i] }
        catch { Write-KuraLog "[$($states[$i].Def.id)] Unexpected error: $($_.Exception.Message)" -Level Error }
    }
    # Re-read installed versions (keep the latest-version lookups we already did)
    $states = @(Get-AllStates -Defs $defs -Previous $states)
}
Write-KuraLog "=== Finished. Log: $LogFile ===" -Level Info
